language: php
php:
  - 7.1
  - 7.2

sudo: required
services:
- docker

env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --optimize-autoloader"
  - TASK_TESTS=1
  - TASK_TESTS_COVERAGE=0
  - TASK_CS=1
  - TASK_SCA=0
  matrix:
#  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo
install:
- composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
script:
- composer phpunit
- composer phpstan
- composer cs-check
after_success:
- bash <(curl -s https://codecov.io/bash)
